### ISSUE TITLE
Tips on debugging?

### ISSUE THREAD

**Issue by bcomnes** [klaemo/nova-standardjs#1]
I installed the plugin, opened a project with standard installed as a dev dependency, and the dependencies installed, but I'm still not seeing any inline lint issues popping up. 

Is there some kind of debugging output I can inspect for errors?

**Comment by bcomnes** [comment]
Only error I see is this

<img width="1003" alt="Screenshot 2023-04-05 at 8 27 42 AM" src="https://user-images.githubusercontent.com/166301/230112037-920ad489-d94f-46b1-8caa-361d6a484752.png">

**Comment by klaemo** [comment]
Honestly, no idea. I’m not using Nova anymore.Am 05.04.2023 um 16:28 schrieb Bret Comnes ***@***.***>:﻿
Only error I see is this

his:

**Comment by bcomnes** [comment]
I'll see if I can fire it up in a dev environment to see if it's something fixable at some point.
